version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: btlrbtlr
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
